server:
  port: 8083
spring:
  datasource:
    system-datasource: #系统运行库
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//192.168.1.126:1522/xe
      username: 'test'
      password: 'test'
    czbz-datasource: #标准表空间
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//192.168.1.126:1522/xe
      username: 'USR_CODE'
      password: 'BOSSSOFT123'
    main-datasource: #主数据源
      driverClassName: oracle.jdbc.driver.OracleDriver
      username: 'USR_MAIN'
      password: 'USR_MAIN'
      url: jdbc:oracle:thin:@//192.168.1.126:1522/xe
  redis: #redis 配置
    host: localhost
    port: 6379

logging:
  level:
    com:
      bosssoft:
        datacentre: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@127.0.0.1:8761/eureka/
service:
#    用户中心登录验证
    loginUrl: http://localhost:8282/appframe-web/u/submitLogin.do
#    用户中心根据用户信息获取菜单接口
    menuUrl: http://localhost:8282/appframe-web/platform/appframe/afauser/getMenuRelation.do
    primaryKey: GUID

swagger: 
  enable: true

