server:
  port: 8082
spring:
  datasource:
    system-datasource: #系统运行库
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//127.0.0.1:1522/xe
      username: '{cipher}23665912840dfa7756405461a8c9f4c88139c245bac60dc78a2c2828d5e21ea9'
      password: '{cipher}23665912840dfa7756405461a8c9f4c88139c245bac60dc78a2c2828d5e21ea9'
    czbz-datasource: #参照标准库
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@//127.0.0.1:1522/xe
      username: '{cipher}9f1f96fe7e9c91ef4733b04f37794476a86cdee56582591e04e638679d62fe4e'
      password: '{cipher}9f1f96fe7e9c91ef4733b04f37794476a86cdee56582591e04e638679d62fe4e'

  redis: #redis 配置
    host: localhost
    port: 6379

logging:
  level:
    com:
      bosssoft:
        datacentre: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@58.22.61.222:31004/eureka/

service:
#    用户中心登录验证
    loginUrl: http://localhost:8282/appframe-web/u/submitLogin.do
#    用户中心根据用户信息获取菜单接口
    menuUrl: http://localhost:8282/appframe-web/platform/appframe/afauser/getMenuRelation.do

swagger: 
  enable: false

