server:
  port: 9090
  context-path: /form
  
spring:
  application:
    name: form-design
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeesite?useSSL=true&autoReconnect=true&initialTimeout=3&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

    #redis配置
  redis:
    host: localhost
    port: 6379
  #缓存配置
  cache:
    type: redis

logging:
  level:
    com:
      bosssoft:
        HFGYDX:
          FORM:
            mapper: debug
            
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:8761/eureka/
      
service:
    #作为独立微服务运行代码生成路径
    onesPath: E:\BOSI\BOSIFiles\demo
    #不作为独立微服务运行代码生成路径
    codePath: E:\BOSI\BOSIFiles\codes
    loginUrl: http://localhost:8080/appframe-web/u/submitLogin.do
    menuUrl: http://localhost:8080/appframe-web/platform/appframe/afauser/getMenuRelation.do

  
mybatis:
  mapper-locations: classpath:gen/*.xml
  type-aliases-package: com.bosssoft.HFGYDX.FORM.model

swagger: 
  enable: true

